const customFeatures = [
  {
    id: 0,
    name: "API Integration",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    turnaroundTime: 5,
    cesTurnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
    description:
      "Pipe in dynamic content within a unit via external data source",
    objective: "Primary: Awareness or Conversion",
    bestPractices:
      "Requires client to supply desired API credentials. For retail clients, need external data source to ensure daily product offerings daily based on store availabilities. Can also be used in conjuction with Click2Cart functionality.",
    programmatic: "Feasible",
    clientRequirements: "Client Supplied API + Credentials",
  },
  {
    id: 1,
    name: "Dynamic Responsive Creative",
    abbrev: "null",
    minSpend: 125000,
    highImpact: true,
    turnaroundTime: 7,
    cesTurnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
    description:
      "Dynamically pull in weather condition or time of day directly within the creative based on the user's location.",
    objective: "Primary: Awareness Recommended Metrics: CTR, Engagement",
    bestPractices:
      "Requires API connection to weather app. List of weather that can be tracked can be found here. Creative can be dynamically served in the adserver based on time of day. Can be leveraged within In-Screen/In-Image blend.",
    programmatic: "TBD",
    clientRequirements: "List of Permutations and triggers",
  },
  {
    id: 2,
    name: "Countdown",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 3,
    cesTurnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 3,
    name: "Extended Rollover",
    abbrev: "null",
    minSpend: 25000,
    highImpact: true,
    turnaroundTime: 3,
    cesRequired: false,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 4,
    name: "Scrollable Text",
    abbrev: "null",
    minSpend: 25000,
    highImpact: true,
    turnaroundTime: 3,
    cesRequired: false,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 5,
    name: "Social Integration",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    turnaroundTime: 3,
    cesTurnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 6,
    name: "Interactive Scroll",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 5,
    cesRequired: true,
    cesTurnaroundTime: 1,
    floorCPM: 3,
    openCPM: 4,
  },
  {
    id: 7,
    name: "Interactive Carousel",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 5,
    cesRequired: true,
    cesTurnaroundTime: 1,
    floorCPM: 3,
    openCPM: 4,
  },
  {
    id: 8,
    name: "Interactive Slider",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 5,
    cesRequired: true,
    cesTurnaroundTime: 1,
    floorCPM: 3,
    openCPM: 4,
  },
  {
    id: 9,
    name: "Interactive Quiz/Poll",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    turnaroundTime: 5,
    cesTurnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 10,
    name: "360 Interactive",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 5,
    cesRequired: true,
    cesTurnaroundTime: 1,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 11,
    name: "Hotspot Integration 3D",
    abbrev: "null",
    minSpend: 250000,
    highImpact: true,
    turnaroundTime: 15,
    cesTurnaroundTime: 3,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 12,
    name: "Hotspot Integration no-3D",
    abbrev: "null",
    minSpend: 225000,
    highImpact: true,
    turnaroundTime: 10,
    cesTurnaroundTime: 3,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 13,
    name: "Map Integration",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    turnaroundTime: 5,
    cesTurnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 14,
    name: "Multiple CTAs",
    abbrev: "null",
    minSpend: 75000,
    highImpact: true,
    turnaroundTime: 3,
    cesTurnaroundTime: 3,
    cesRequired: true,
    floorCPM: 0,
    openCPM: 0,
  },
  {
    id: 15,
    name: "Multiple Tune-ins",
    abbrev: "null",
    minSpend: 25000,
    highImpact: true,
    turnaroundTime: 2,
    cesRequired: false,
    floorCPM: 0,
    openCPM: 0,
  },
  {
    id: 16,
    name: "Expandable Accordian",
    abbrev: "null",
    minSpend: 125000,
    highImpact: true,
    turnaroundTime: 5,
    cesTurnaroundTime: 3,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 17,
    name: "Lightbox - Standard Shoppable",
    abbrev: "null",
    minSpend: 125000,
    highImpact: true,
    turnaroundTime: 5,
    cesTurnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 18,
    name: "Lightbox - Custom Shoppable",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    turnaroundTime: 10,
    cesTurnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 19,
    name: "Lightbox - Multiple Click-outs",
    abbrev: "null",
    minSpend: 125000,
    highImpact: true,
    turnaroundTime: 5,
    cesTurnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 20,
    name: "Lightbox - Multiple Videos",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    turnaroundTime: 5,
    cesTurnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 21,
    name: "Lightbox - Host Micro-site",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 10,
    cesTurnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 22,
    name: "In-image - Color Matching",
    abbrev: "null",
    minSpend: 125000,
    highImpact: true,
    turnaroundTime: 5,
    cesTurnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
  {
    id: 23,
    name: "In-image - Facial Recognition",
    abbrev: "null",
    minSpend: 225000,
    highImpact: true,
    turnaroundTime: 5,
    cesTurnaroundTime: 10,
    cesRequired: true,
    floorCPM: 2,
    openCPM: 2,
  },
];

export default customFeatures;
