/* eslint-disable import/no-anonymous-default-export */
var dmp = [
  {
    id: 0,
    dataType: "GumGum First Part (Contextual)",
    minSpend: 25000,
    tier25Cpm: 0,
    tier50Cpm: 0,
    tier75Cpm: 0,
    tier100Cpm: 0,
    tier125Cpm: 0,
    tier200Cpm: 0,
    tier300Cpm: 0,
    noVoiceCpm: 0,

    tableInfo: [
      { column1: "Unlocked" },
      { column2: "Unlocked" },
      { column3: "Unlocked" },
      { column4: "Unlocked" },
      { column5: "Unlocked" },
      { column6: "Unlocked" },
      { column7: "Unlocked" },
      { column8: "Locked" },
    ],
  },
  {
    id: 1,
    dataType: "Lotame LDX ($0.20)",
    minSpend: 25000,
    tier25Cpm: 0.2,
    tier50Cpm: 0.2,
    tier75Cpm: 0.2,
    tier100Cpm: 0,
    tier125Cpm: 0,
    tier200Cpm: 0,
    tier300Cpm: 0,
    noVoiceCpm: 0.2,
    tableInfo: [
      { column1: "$0.20 CPM Upcharge" },
      { column2: "$0.20 CPM Upcharge" },
      { column3: "$0.20 CPM Upcharge" },
      { column4: "Unlocked" },
      { column5: "Unlocked" },
      { column6: "Unlocked" },
      { column7: "Unlocked" },
      { column8: "$0.20 CPM Upcharge" },
    ],
  },
  {
    id: 2,
    dataType: "3rd Party Branded Data",
    minSpend: 25000,
    tier25Cpm: 1,
    tier50Cpm: 1,
    tier75Cpm: 1,
    tier100Cpm: 0.5,
    tier125Cpm: 0.5,
    tier200Cpm: 0,
    tier300Cpm: 0,
    noVoiceCpm: 1,
    tableInfo: [
      { column1: "$1.00 CPM Upcharge" },
      { column2: "$1.00 CPM Upcharge" },
      { column3: "$1.00 CPM Upcharge" },
      { column4: "$0.50 CPM Upcharge" },
      { column5: "$0.50 CPM Upcharge" },
      { column6: "Unlocked" },
      { column7: "Unlocked" },
      { column8: "$1.00 CPM Upcharge" },
    ],
  },
  {
    id: 3,
    dataType: "Client Ad Serving Fee's (DCM, IAS, DV, Other)",
    minSpend: 25000,
    tier25Cpm: 0.15,
    tier50Cpm: 0.15,
    tier75Cpm: 0.15,
    tier100Cpm: 0,
    tier125Cpm: 0,
    tier200Cpm: 0,
    tier300Cpm: 0,
    noVoiceCpm: 0.15,
    tableInfo: [
      { column1: "" },
      { column2: "$0.15 CPM Upcharge" },
      { column3: "$0.15 CPM Upcharge" },
      { column4: "$0.15 CPM Upcharge" },
      { column5: "Unlocked" },
      { column6: "Unlocked" },
      { column7: "Unlocked" },
      { column8: "$0.15 CPM Upcharge" },
    ],
  },
  {
    id: 4,
    dataType: "Advertiser First Part Data Ingestion",
    minSpend: 25000,
    tier25Cpm: 1,
    tier50Cpm: 1,
    tier75Cpm: 1,
    tier100Cpm: 1,
    tier125Cpm: 1,
    tier200Cpm: 1,
    tier300Cpm: 0,
    noVoiceCpm: 1,
    tableInfo: [
      { column1: "" },
      { column2: "$1.00 CPM Upcharge" },
      { column3: "$1.00 CPM Upcharge" },
      { column4: "$1.00 CPM Upcharge" },
      { column5: "$1.00 CPM Upcharge" },
      { column6: "$1.00 CPM Upcharge" },
      { column7: "Unlocked" },
      { column8: "$1.00 CPM Upcharge" },
    ],
  },
  {
    id: 5,
    dataType: "ABM Data",
    minSpend: 100000,
    tier25Cpm: "locked",
    tier50Cpm: "locked",
    tier75Cpm: "locked",
    tier100Cpm: 3,
    tier125Cpm: 3,
    tier200Cpm: 3,
    tier300Cpm: 3,
    noVoiceCpm: "locked",
    tableInfo: [
      { column1: "" },
      { column2: "" },
      { column3: "" },
      { column4: "$3.00 CPM Upcharge" },
      { column5: "$3.00 CPM Upcharge" },
      { column6: "$3.00 CPM Upcharge" },
      { column7: "$3.00 CPM Upcharge" },
      { column8: "" },
    ],
  },
];

export default dmp;
