/* eslint-disable import/no-anonymous-default-export */
var dmp = [
  {
    id: 0,
    dataType: "GumGum First Part (Contextual)",
    minSpend: 0,
    tableInfo: [
      { column1: "Unlocked" },
      { column2: "Unlocked" },
      { column3: "Unlocked" },
      { column4: "Unlocked" },
      { column5: "Unlocked" },
      { column6: "Unlocked" },
      { column7: "Unlocked" },
      { column8: "Locked" },
    ],
  },
  {
    id: 1,
    dataType: "Lotame LDX ($0.20)",
    minSpend: 0,
    tableInfo: [
      { column1: "$0.20 CPM Upcharge" },
      { column2: "Unlocked" },
      { column3: "Unlocked" },
      { column4: "Unlocked" },
      { column5: "Unlocked" },
      { column6: "Unlocked" },
      { column7: "Unlocked" },
      { column8: "Locked" },
    ],
  },
  {
    id: 2,
    dataType: "3rd Party Branded Data",
    minSpend: 0,
    tableInfo: [
      { column1: "$0.50 CPM Upcharge" },
      { column2: "$0.50 CPM Upcharge" },
      { column3: "Unlocked" },
      { column4: "Unlocked" },
      { column5: "Unlocked" },
      { column6: "Unlocked" },
      { column7: "Unlocked" },
      { column8: "Locked" },
    ],
  },
  {
    id: 3,
    dataType: "Custom Audiences",
    minSpend: 100000,
    tableInfo: [
      { column1: "" },
      { column2: "$1.00 CPM Upcharge" },
      { column3: "Unlocked" },
      { column4: "Unlocked" },
      { column5: "Unlocked" },
      { column6: "Unlocked" },
      { column7: "Unlocked" },
      { column8: "Locked" },
    ],
  },
  {
    id: 4,
    dataType: "Advertiser First Part Data Ingestion",
    minSpend: 100000,
    tableInfo: [
      { column1: "" },
      { column2: "$1.00 CPM Upcharge" },
      { column3: "Unlocked" },
      { column4: "Unlocked" },
      { column5: "Unlocked" },
      { column6: "Unlocked" },
      { column7: "Unlocked" },
      { column8: "Locked" },
    ],
  },
  {
    id: 5,
    dataType: "ABM Data",
    minSpend: 100000,
    tableInfo: [
      { column1: "" },
      { column2: "$3.00 CPM Upcharge" },
      { column3: "$3.00 CPM Upcharge" },
      { column4: "Unlocked" },
      { column5: "Unlocked" },
      { column6: "Unlocked" },
      { column7: "Unlocked" },
      { column8: "Locked" },
    ],
  },
];

export default dmp;
