const unitTypes = [
  {
    id: 0,
    name: "In-Screen",
    abbrev: "IS",
    minSpend: 25000,
    highImpact: false,
    turnaroundTime: 2,
    cesRequired: false,
    floorCPM: 700,
    floorVCPM: 1200,
    openCPM: 850,
    customizable: true,
    customFeatures: [
      0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 21,
    ],
  },
  {
    id: 1,
    name: "In-Image",
    abbrev: "II",
    minSpend: 25000,
    highImpact: false,
    turnaroundTime: 2,
    cesRequired: false,
    floorCPM: 700,
    floorVCPM: 1000,
    openCPM: 850,
    customizable: true,
    customFeatures: [
      0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 21, 22, 23,
    ],
  },
  {
    id: 2,
    name: "In-Screen Expandable Video",
    abbrev: "ISXV",
    minSpend: 25000,
    highImpact: false,
    turnaroundTime: 2,
    cesRequired: true,
    floorCPM: 1150,
    floorVCPM: 1600,
    openCPM: 1450,
    customizable: true,
    customFeatures: [2, 4, 14, 15],
  },
  {
    id: 3,
    name: "6-Sec Canvas Video",
    abbrev: "6sCNV",
    minSpend: 25000,
    highImpact: false,
    turnaroundTime: 2,
    cesRequired: false,
    floorCPM: 1300,
    floorVCPM: 1850,
    openCPM: 1500,
    customizable: false,
  },
  {
    id: 4,
    name: "In-Screen Frame",
    abbrev: "ISF",
    minSpend: 25000,
    highImpact: false,
    turnaroundTime: 2,
    cesRequired: false,
    floorCPM: 1000,
    floorVCPM: 1425,
    openCPM: 1200,
    customizable: true,
    customFeatures: [0, 1, 2, 5, 13, 14, 15],
  },
  {
    id: 5,
    name: "In-Screen Expandable Corner",
    abbrev: "ISXC",
    minSpend: 25000,
    highImpact: false,
    turnaroundTime: 2,
    cesRequired: false,
    floorCPM: 750,
    floorVCPM: 1050,
    openCPM: 950,
    customizable: true,
    customFeatures: [2, 15],
  },
  {
    id: 6,
    name: "In-Image Canvas",
    abbrev: "IIC",
    minSpend: 74000,
    highImpact: true,
    turnaroundTime: 3,
    cesRequired: false,
    floorCPM: 1300,
    floorVCPM: 1850,
    openCPM: 1500,
    customizable: true,
    customFeatures: [
      0, 1, 2, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 21, 22, 23,
    ],
  },
  {
    id: 7,
    name: "In-Image Expandable",
    abbrev: "IIX",
    minSpend: 74000,
    highImpact: true,
    turnaroundTime: 3,
    cesRequired: false,
    floorCPM: 1000,
    floorVCPM: 1425,
    openCPM: 1200,
    customizable: true,
    customFeatures: [
      0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 22, 23,
    ],
  },
  {
    id: 8,
    name: "In-Screen Expandable",
    abbrev: "ISX",
    minSpend: 74000,
    highImpact: true,
    turnaroundTime: 3,
    cesRequired: false,
    floorCPM: 1150,
    floorVCPM: 1600,
    openCPM: 1450,
    customizable: true,
    customFeatures: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
  },
  {
    id: 9,
    name: "Desktop Skin",
    abbrev: "null",
    minSpend: 200000,
    highImpact: true,
    turnaroundTime: 5,
    cesRequired: true,
    floorCPM: 2200,
    floorVCPM: "TBD",
    openCPM: 2500,
    customizable: false,
  },
  {
    id: 10,
    name: "Mobile Skin",
    abbrev: "null",
    minSpend: 200000,
    highImpact: true,
    turnaroundTime: 5,
    cesRequired: true,
    floorCPM: 1800,
    floorVCPM: "TBD",
    openCPM: 2100,
    customizable: false,
  },
  {
    id: 11,
    name: "Mobile Scroller",
    abbrev: "null",
    minSpend: 200000,
    highImpact: true,
    turnaroundTime: 3,
    cesRequired: true,
    floorCPM: 800,
    floorVCPM: "TBD",
    openCPM: 1000,
    customizable: false,
  },
  {
    id: 12,
    name: "Gumgum Standard",
    abbrev: "null",
    minSpend: 25000,
    highImpact: false,
    turnaroundTime: 2,
    cesRequired: false,
    floorCPM: 350,
    floorVCPM: 500,
    openCPM: 500,
    customizable: false,
  },
  {
    id: 13,
    name: "Gumgum Display",
    abbrev: "null",
    minSpend: 25000,
    highImpact: false,
    turnaroundTime: 2,
    cesRequired: false,
    floorCPM: 250,
    floorVCPM: "Custom rate",
    openCPM: 350,
    customizable: false,
  },
  {
    id: 14,
    name: "Gumgum Native",
    abbrev: "null",
    minSpend: 25000,
    highImpact: false,
    turnaroundTime: 0,
    cesRequired: true,
    floorCPM: 700,
    floorVCPM: "TBD",
    openCPM: 1000,
    customizable: false,
  },
  {
    id: 15,
    name: "Gumgum Social",
    abbrev: "null",
    minSpend: 25000,
    highImpact: false,
    turnaroundTime: 0,
    cesRequired: true,
    floorCPM: 950,
    floorVCPM: "TBD",
    openCPM: 1200,
    customizable: false,
  },
  {
    id: 16,
    name: "In-Article Shoppable",
    abbrev: "IAS",
    minSpend: 25000,
    highImpact: false,
    turnaroundTime: 2,
    cesRequired: true,
    floorVCPM: 1100,
    floorCPM: 800,
    openCPM: 1000,
    customizable: false,
  },
  {
    id: 17,
    name: "In-Article Video",
    abbrev: "IAV",
    minSpend: 25000,
    highImpact: false,
    turnaroundTime: 0,
    cesRequired: true,
    floorCPM: 950,
    floorVCPM: 1100,
    openCPM: 1200,
    customizable: false,
  },
  {
    id: 18,
    name: "In-Video Snipe",
    abbrev: "IVS",
    minSpend: 0,
    highImpact: true,
    turnaroundTime: 7,
    cesRequired: true,
    floorCPM: 1400,
    floorVCPM: 2150,
    openCPM: 1700,
    customizable: false,
  },
];
const customFeatures = [
  {
    id: 0,
    name: "API Integration",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    turnaroundTime: 7,
    cesTurnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 1,
    name: "Dynamic Responsive Creative",
    abbrev: "null",
    minSpend: 125000,
    highImpact: true,
    turnaroundTime: 7,
    cesTurnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 2,
    name: "Countdown",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 3,
    cesTurnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 3,
    name: "Extended Rollover",
    abbrev: "null",
    minSpend: 25000,
    highImpact: true,
    turnaroundTime: 3,
    cesRequired: false,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 4,
    name: "Scrollable Text",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 3,
    cesRequired: false,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 5,
    name: "Social Integration",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    turnaroundTime: 3,
    cesTurnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 6,
    name: "Interactive Scroll",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 5,
    cesRequired: true,
    floorCPM: 300,
    floorVCPM: 300,
    openCPM: 400,
  },
  {
    id: 7,
    name: "Interactive Carousel",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 5,
    cesRequired: true,
    floorCPM: 300,
    floorVCPM: 300,
    openCPM: 400,
  },
  {
    id: 8,
    name: "Interactive Slider",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 5,
    cesRequired: true,
    floorCPM: 300,
    floorVCPM: 300,
    openCPM: 400,
  },
  {
    id: 9,
    name: "Interactive Quiz/Poll",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    turnaroundTime: 7,
    cesTurnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 10,
    name: "360 Interactive",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 11,
    name: "Hotspot Integration 3D",
    abbrev: "null",
    minSpend: 250000,
    highImpact: true,
    turnaroundTime: 21,
    cesTurnaroundTime: 3,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 12,
    name: "Hotspot Integration no-3D",
    abbrev: "null",
    minSpend: 225000,
    highImpact: true,
    turnaroundTime: 14,
    cesTurnaroundTime: 3,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 13,
    name: "Map Integration",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    turnaroundTime: 7,
    cesTurnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 14,
    name: "Multiple CTAs",
    abbrev: "null",
    minSpend: 75000,
    highImpact: true,
    turnaroundTime: 3,
    cesTurnaroundTime: 3,
    cesRequired: true,
    floorCPM: 0,
    openCPM: 0,
  },
  {
    id: 15,
    name: "Multiple Tune-ins",
    abbrev: "null",
    minSpend: 25000,
    highImpact: true,
    turnaroundTime: 2,
    cesRequired: false,
    floorCPM: 0,
    openCPM: 0,
  },
  {
    id: 16,
    name: "Expandable Accordian",
    abbrev: "null",
    minSpend: 125000,
    highImpact: true,
    turnaroundTime: 7,
    cesTurnaroundTime: 3,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 17,
    name: "Lightbox - Standard Shoppable",
    abbrev: "null",
    minSpend: 125000,
    highImpact: true,
    turnaroundTime: 7,
    cesTurnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 18,
    name: "Lightbox - Custom Shoppable",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    turnaroundTime: 14,
    cesTurnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 19,
    name: "Lightbox - Multiple Click-outs",
    abbrev: "null",
    minSpend: 125000,
    highImpact: true,
    turnaroundTime: 7,
    cesTurnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 20,
    name: "Lightbox - Multiple Videos",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    turnaroundTime: 7,
    cesTurnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 21,
    name: "Lightbox - Host Micro-site",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    turnaroundTime: 14,
    cesTurnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 22,
    name: "In-image - Color Matching",
    abbrev: "null",
    minSpend: 125000,
    highImpact: true,
    turnaroundTime: 7,
    cesTurnaroundTime: 7,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
  {
    id: 23,
    name: "In-image - Facial Recognition",
    abbrev: "null",
    minSpend: 225000,
    highImpact: true,
    turnaroundTime: 7,
    cesTurnaroundTime: 14,
    cesRequired: true,
    floorCPM: 200,
    floorVCPM: 200,
    openCPM: 200,
  },
];
export { unitTypes, customFeatures };
