const unitTypes = [
  {
    id: 0,
    name: "In-Screen",
    abbrev: "IS",
    minSpend: 25000,
    highImpact: false,
    isCustom: false,
    turnaroundTime: 2,
    cesRequired: false,
  },
  {
    id: 1,
    name: "In-Image",
    abbrev: "II",
    minSpend: 25000,
    highImpact: false,
    isCustom: false,
    turnaroundTime: 2,
    cesRequired: false,
  },
  {
    id: 2,
    name: "In-Screen Expandable Video",
    abbrev: "ISXV",
    minSpend: 25000,
    highImpact: false,
    isCustom: false,
    turnaroundTime: 2,
    cesRequired: true,
  },
  {
    id: 3,
    name: "In-Image Expandable Video",
    abbrev: "IIXV",
    minSpend: 25000,
    highImpact: false,
    isCustom: false,
    turnaroundTime: 2,
    cesRequired: true,
  },
  {
    id: 4,
    name: "6-Sec Canvas Video",
    abbrev: "6sCNV",
    minSpend: 25000,
    highImpact: false,
    isCustom: false,
    turnaroundTime: 2,
    cesRequired: false,
  },
  {
    id: 5,
    name: "In-Screen Frame",
    abbrev: "ISF",
    minSpend: 25000,
    highImpact: false,
    isCustom: false,
    turnaroundTime: 2,
    cesRequired: false,
  },
  {
    id: 0,
    name: "In-Screen Expandable Corner",
    abbrev: "ISXC",
    minSpend: 25000,
    highImpact: false,
    isCustom: false,
    turnaroundTime: 2,
    cesRequired: false,
  },
  {
    id: 6,
    name: "In-Article Shoppable",
    abbrev: "IAS",
    minSpend: 25000,
    highImpact: false,
    isCustom: false,
    turnaroundTime: 2,
    cesRequired: true,
  },
  {
    id: 7,
    name: "In-Image Canvas",
    abbrev: "IIC",
    minSpend: 74000,
    highImpact: true,
    isCustom: false,
    turnaroundTime: 3,
    cesRequired: false,
  },
  {
    id: 8,
    name: "In-Image Expandable",
    abbrev: "IIX",
    minSpend: 74000,
    highImpact: true,
    isCustom: false,
    turnaroundTime: 3,
    cesRequired: false,
  },
  {
    id: 9,
    name: "In-Screen Expandable",
    abbrev: "ISX",
    minSpend: 74000,
    highImpact: true,
    isCustom: false,
    turnaroundTime: 3,
    cesRequired: false,
  },
  {
    id: 10,
    name: "In-Video Snipe",
    abbrev: "IVS",
    minSpend: 0,
    highImpact: true,
    isCustom: false,
    turnaroundTime: 7,
    cesRequired: true,
  },
  {
    id: 11,
    name: "API Integration",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    isCustom: true,
    turnaroundTime: 4,
    cesTurnaroundTime: 7,
    cesRequired: true,
  },
  {
    id: 12,
    name: "Dynamic Responsive Creative",
    abbrev: "null",
    minSpend: 125000,
    highImpact: true,
    isCustom: true,
    turnaroundTime: 4,
    cesTurnaroundTime: 7,
    cesRequired: true,
  },
  {
    id: 13,
    name: "Countdown",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    isCustom: true,
    turnaroundTime: 1,
    cesTurnaroundTime: 7,
    cesRequired: true,
  },
  {
    id: 14,
    name: "Social Integration",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    isCustom: true,
    turnaroundTime: 1,
    cesTurnaroundTime: 7,
    cesRequired: true,
  },
  {
    id: 15,
    name: "Interactive Scroll",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    isCustom: true,
    turnaroundTime: 3,
    cesTurnaroundTime: 1,
    cesRequired: true,
  },
  {
    id: 16,
    name: "Interactive Carousel",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    isCustom: true,
    turnaroundTime: 3,
    cesTurnaroundTime: 1,
    cesRequired: true,
  },
  {
    id: 17,
    name: "Interactive Slider",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    isCustom: true,
    turnaroundTime: 3,
    cesTurnaroundTime: 1,
    cesRequired: true,
  },
  {
    id: 18,
    name: "Interactive Quiz/Poll",
    abbrev: "null",
    minSpend: 150000,
    highImpact: true,
    isCustom: true,
    turnaroundTime: 4,
    cesTurnaroundTime: 7,
    cesRequired: true,
  },
  {
    id: 19,
    name: "360 Interactive",
    abbrev: "null",
    minSpend: 100000,
    highImpact: true,
    isCustom: true,
    turnaroundTime: 4,
    cesTurnaroundTime: 1,
    cesRequired: true,
  },
  {
    id: 20,
    name: "Hotspot Integration 3D",
    abbrev: "null",
    minSpend: 250000,
    highImpact: true,
    isCustom: true,
    turnaroundTime: 12,
    cesTurnaroundTime: 3,
    cesRequired: true,
  },
  {
    id: 20,
    name: "Hotspot Integration 3D",
    abbrev: "null",
    minSpend: 250000,
    highImpact: true,
    isCustom: true,
    turnaroundTime: 12,
    cesTurnaroundTime: 3,
    cesRequired: true,
  },
];

export { unitTypes };
